# Generated by Django 2.0.7 on 2018-07-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_choice1',
        ),
    ]
