# Generated by Django 2.0.7 on 2018-07-10 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaire',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 16, 33, 43, 669945), help_text='结束时间'),
        ),
    ]
