# Generated by Django 2.0.7 on 2018-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_question_choice1'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
