# Generated by Django 2.0.7 on 2018-07-10 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180710_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaire',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 16, 34, 5, 278321), help_text='结束时间'),
        ),
    ]
