# Generated by Django 2.0.7 on 2018-07-11 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180710_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_drawn',
            field=models.CharField(default='未中奖', help_text='奖品', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='问题内容', max_length=200),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 13, 27, 25, 97987), help_text='结束时间'),
        ),
    ]
