# Generated by Django 2.0.7 on 2018-07-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180706_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_name', models.CharField(max_length=200)),
                ('answer_email', models.IntegerField(default=0)),
                ('answer_number', models.IntegerField(default=0)),
            ],
        ),
    ]
