# Generated by Django 2.0.7 on 2018-07-11 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180711_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(help_text='答案内容，需要加上选项字母，如"A.答案内容"', max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, help_text='答案分数，正确答案为1分，错误的多选为-5分'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionaire',
            field=models.ForeignKey(help_text='问题问卷', on_delete=django.db.models.deletion.CASCADE, to='polls.Questionaire'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 13, 30, 39, 128783), help_text='结束时间'),
        ),
    ]
