# Generated by Django 2.0.7 on 2018-07-11 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180711_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 13, 37, 59, 873619)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, help_text='答案分数，正确为一分，多选题非正确选项为-5分'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 13, 37, 59, 857822), help_text='结束时间'),
        ),
    ]
