# Generated by Django 2.0.7 on 2018-07-11 16:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180711_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 16, 12, 40, 622515)),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 16, 12, 40, 591380), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='questionaire_uid',
            field=models.BigIntegerField(default=0, verbose_name='序号'),
        ),
    ]
