# Generated by Django 2.0.7 on 2018-07-11 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180711_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 16, 12, 52, 774125)),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 16, 12, 52, 759143), verbose_name='结束时间'),
        ),
    ]
