# Generated by Django 2.0.7 on 2018-07-12 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180711_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_choice',
            field=models.CharField(default='', max_length=200, verbose_name='答题人的答案'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_drawn',
            field=models.CharField(default='未中奖', max_length=200, verbose_name='奖品'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_email',
            field=models.EmailField(default=0, max_length=254, verbose_name='答案人人数'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_name',
            field=models.CharField(max_length=200, verbose_name='答题人姓名'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_number',
            field=models.IntegerField(default=0, verbose_name='答题人电话号码'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_phonenumber',
            field=models.BigIntegerField(default=0, verbose_name='答案人电话号码'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='drawn',
            field=models.BooleanField(default=False, verbose_name='是否中奖'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(help_text='需要加上选项字母，如"A.答案内容"', max_length=200, verbose_name='答案内容'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, help_text='正确为一分，多选题非正确选项为-5分', verbose_name='答案分数'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 12, 16, 16, 54, 582592), verbose_name='问题创建时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='问题内容', max_length=200, verbose_name='问题内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionaire',
            field=models.ForeignKey(help_text='问题所在问卷', on_delete=django.db.models.deletion.CASCADE, to='polls.Questionaire'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sf',
            field=models.BooleanField(default=False, verbose_name='是否多选'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 16, 16, 54, 551614), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='questionaire_text',
            field=models.CharField(max_length=200, verbose_name='问卷名称'),
        ),
    ]
